server:
  port: 8082

spring:
  application:
    name: synapsis-projet
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        preferIpAddress: true
    client:
        registryFetchIntervalSeconds: 50
        serviceUrl:
            defaultZone: http://52.57.12.223:8761/eureka/